=== balajinix/grad_school/630-DB/xhive/src/samples/data/manual/editor_info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="editor_info">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="chapter" minOccurs='1' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="chapter">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="editor" type="xs:string"/>
        <xs:element name="date" type="xs:date"/>
        <xs:element name="approved">
          <xs:simpleType>
           <xs:restriction base = "xs:string">
             <xs:enumeration value="yes"/>
             <xs:enumeration value="no"/>
           </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== balajinix/grad_school/630-DB/xhive/src/samples/data/manual/un_charter_editor_info.xml
<editor_info 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation='editor_info.xsd'>

  <chapter id="/UN Charter/UN Charter - Chapter 1">
    <editor>William</editor>
    <date>2003-03-07</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 2">
    <editor>Percy</editor>
    <date>2003-03-08</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 3">
    <editor>William</editor>
    <date>2003-03-19</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 4">
    <editor>William</editor>
    <date>2003-03-12</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 5">
    <editor>William</editor>
    <date>2003-04-02</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 6">
    <editor>John</editor>
    <date>2003-03-01</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 7">
    <editor>Michael</editor>
    <date>2002-12-31</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 8">
    <editor>John</editor>
    <date>2003-03-06</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 9">
    <editor>John</editor>
    <date>2003-03-18</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 10">
    <editor>Derek</editor>
    <date>2003-03-12</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 11">
    <editor>William</editor>
    <date>2003-03-01</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 12">
    <editor>Robert</editor>
    <date>2003-03-07</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 13">
    <editor>William</editor>
    <date>2003-03-07</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 14">
    <editor>William</editor>
    <date>2003-03-07</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 15">
    <editor>John</editor>
    <date>2003-02-16</date>
    <approved>yes</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 16">
    <editor>John</editor>
    <date>2003-03-17</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 17">
    <editor>William</editor>
    <date>2003-03-08</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 18">
    <editor>William</editor>
    <date>2003-03-06</date>
    <approved>no</approved>
  </chapter>

  <chapter id="/UN Charter/UN Charter - Chapter 18">
    <editor>William</editor>
    <date>2003-03-07</date>
    <approved>yes</approved>
  </chapter>

</editor_info>
