=== balajinix/grad_school/630-DB/xhive/src/samples/data/manual/un_charter_chapter.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT article (para)>
<!ATTLIST article
	number CDATA #REQUIRED
>
<!ELEMENT chapter (title, (section+ | article+))>
<!ATTLIST chapter
	number CDATA #REQUIRED
>
<!ELEMENT item (para)>
<!ELEMENT list (item+)>
<!ELEMENT para (#PCDATA | list)*>
<!ELEMENT section (title, article+)> 
<!ELEMENT title (#PCDATA)>

=== balajinix/grad_school/630-DB/xhive/src/samples/data/manual/un_charter_chapter1_withDTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE chapter PUBLIC "UN Charter" "un_charter_chapter.dtd">
<chapter number="1">
	<title>PURPOSES AND PRINCIPLES</title>
	<article number="1">
		<para>
				The Purposes of the United Nations are:
				<list>
				<item>
					<para>To maintain international peace and security, and to that end: to take effective collective measures for the prevention and removal of threats to the peace, and for the suppression of acts of aggression or other breaches of the peace, and to bring about by peaceful means, and in conformity with the principles of justice and international law, adjustment or settlement of international disputes or situations which might lead to a breach of the peace;</para>
				</item>
				<item>
					<para>To develop friendly relations among nations based on respect for the principle of equal rights and self-determination of peoples, and to take other appropriate measures to strengthen universal peace;</para>
				</item>
				<item>
					<para>To achieve international co-operation in solving international problems of an economic, social, cultural, or humanitarian character, and in promoting and encouraging respect for human rights and for fundamental freedoms for all without distinction as to race, sex, language, or religion; and</para>
				</item>
				<item>
					<para>To be a centre for harmonizing the actions of nations in the attainment of these common ends.</para>
				</item>
			</list>
		</para>
	</article>
	<article number="2">
		<para>
				The Organization and its Members, in pursuit of the Purposes stated in Article 1, shall act in accordance with the following Principles.
				<list>
				<item>
					<para>The Organization is based on the principle of the sovereign equality of all its Members.</para>
				</item>
				<item>
					<para>All Members, in order to ensure to all of them the rights and benefits resulting from membership, shall fulfill in good faith the obligations assumed by them in accordance with the present Charter.</para>
				</item>
				<item>
					<para>All Members shall settle their international disputes by peaceful means in such a manner that international peace and security, and justice, are not endangered.</para>
				</item>
				<item>
					<para>All Members shall refrain in their international relations from the threat or use of force against the territorial integrity or political independence of any state, or in any other manner inconsistent with the Purposes of the United Nations.</para>
				</item>
				<item>
					<para>All Members shall give the United Nations every assistance in any action it takes in accordance with the present Charter, and shall refrain from giving assistance to any state against which the United Nations is taking preventive or enforcement action.</para>
				</item>
				<item>
					<para>The Organization shall ensure that states which are not Members of the United Nations act in accordance with these Principles so far as may be necessary for the maintenance of international peace and security.</para>
				</item>
				<item>
					<para>Nothing contained in the present Charter shall authorize the United Nations to intervene in matters which are essentially within the domestic jurisdiction of any state or shall require the Members to submit such matters to settlement under the present Charter; but this principle shall not prejudice the application of enforcement measures under Chapter Vll.</para>
				</item>
			</list>
		</para>
	</article>
</chapter>
